name: Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Gen LFS Cache Key File
      run: git lfs ls-files -l > lsf-cache-key
    - name: Cache Git LFS
      uses: actions/cache@v1
      id: cache-git-lfs
      with:
        path: .git/lfs
        key: ${{ runner.os }}-${{ hashFiles('**/lsf-cache-key') }}
    - name: Git LFS
      if: steps.cache-git-lfs.cache-hit != 'true'
      run: git lfs pull
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -e .[test]
    - name: Install Blender
      run: |
        sudo snap install blender --channel=2.93lts/stable --classic
    - name: Convert Assets
      run: |
        blender --version
        pman build
    - name: Run Tests
      run: |
        python -m pytest
    - name: Build Binary Distributions
      run: |
        blender --version
        pman dist --skip-installers
    - name: Publish Windows Binary
      uses: josephbmanley/butler-publish-itchio-action@v1.0.1
      if: github.ref == 'refs/heads/master'
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows-dev
        ITCH_GAME: mercury
        ITCH_USER: mogurijin
        PACKAGE: build/win_amd64
    - name: Publish Linux Binary
      uses: josephbmanley/butler-publish-itchio-action@v1.0.1
      if: github.ref == 'refs/heads/master'
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux-dev
        ITCH_GAME: mercury
        ITCH_USER: mogurijin
        PACKAGE: build/manylinux2010_x86_64
